; Actual characters

	charmap " ", $00
	charmap "あ", $01
	charmap "い", $02
	charmap "う", $03
	charmap "え", $04
	charmap "お", $05
	charmap "か", $06
	charmap "き", $07
	charmap "く", $08
	charmap "け", $09
	charmap "こ", $0a
	charmap "さ", $0b
	charmap "し", $0c
	charmap "す", $0d
	charmap "せ", $0e
	charmap "そ", $0f
	charmap "た", $10
	charmap "ち", $11
	charmap "つ", $12
	charmap "て", $13
	charmap "と", $14
	charmap "な", $15
	charmap "に", $16
	charmap "ぬ", $17
	charmap "ね", $18
	charmap "の", $19
	charmap "は", $1a
	charmap "ひ", $1b
	charmap "ふ", $1c
	charmap "へ", $1d
	charmap "ほ", $1e
	charmap "ま", $1f
	charmap "み", $20
	charmap "む", $21
	charmap "め", $22
	charmap "も", $23
	charmap "や", $24
	charmap "ゆ", $25
	charmap "よ", $26
	charmap "ら", $27
	charmap "り", $28
	charmap "る", $29
	charmap "れ", $2a
	charmap "ろ", $2b
	charmap "わ", $2c
	charmap "を", $2d
	charmap "ん", $2e
	charmap "が", $2f
	charmap "ぎ", $30
	charmap "ぐ", $31
	charmap "げ", $32
	charmap "ご", $33
	charmap "ざ", $34
	charmap "じ", $35
	charmap "ず", $36
	charmap "ぜ", $37
	charmap "ぞ", $38
	charmap "だ", $39
	charmap "ぢ", $3a
	charmap "づ", $3b
	charmap "で", $3c
	charmap "ど", $3d
	charmap "ば", $3e
	charmap "び", $3f
	charmap "ぶ", $40
	charmap "べ", $41
	charmap "ぼ", $42
